import React from 'react'
import { LeftArrow, RightArrow } from '@components/icons'
import { Swiper, SwiperSlide } from 'swiper/react'

import 'swiper/css'

function SliderSection() {
  const [swiperRef, setSwiperRef] = React.useState({})

  return (
    <section className="flex flex-col items-center bg-slider bg-cover">
      <div className="mx-auto flex w-full flex-col items-center py-9 px-4 text-center sm:px-36 sm:pt-14">
        <h2 className="mb-20 text-2xl font-bold leading-heading text-white xl:text-[28px] xxl:text-[42px]">
          Get your virtual ownership and earn profits
          <br />
          from Our RoboCo NFT Collection
        </h2>
        <iframe
          className="h-[192px] w-[192px] xl:h-[257px] xl:w-[457px]"
          src="https://www.youtube.com/embed/2BIsykfFbTw"
          title="YouTube Video"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>
        <div className="relative my-10 flex w-[278px] items-center gap-2 p-8 text-center text-xs text-white xl:w-[500px] xl:text-xs xxl:text-base">
          <div
            className="absolute top-10 left-0"
            onClick={() => swiperRef.slidePrev()}
          >
            <LeftArrow />
          </div>
          <div
            className="absolute top-10 right-0"
            onClick={() => swiperRef.slideNext()}
          >
            <RightArrow />
          </div>
          <Swiper onSwiper={setSwiperRef} spaceBetween={50} slidesPerView={1}>
            <SwiperSlide>
              <p>
                Early adopter via NFT ownership will be entitled to a base
                interest rate until the robotics solutions launch, a share of
                future revenue generated by the robots, and partner-exclusive
                service discounts
              </p>
            </SwiperSlide>
            <SwiperSlide>
              <p>
                Early adopter via NFT ownership will be entitled to a base
                interest rate until the robotics solutions launch, a share of
                future revenue generated by the robots, and partner-exclusive
                service discounts
              </p>
            </SwiperSlide>
            <SwiperSlide>
              <p>
                Early adopter via NFT ownership will be entitled to a base
                interest rate until the robotics solutions launch, a share of
                future revenue generated by the robots, and partner-exclusive
                service discounts
              </p>
            </SwiperSlide>
          </Swiper>
        </div>
      </div>
    </section>
  )
}

export default SliderSection
