import React from 'react'
import slider from 'assets/robo/slider.png'
import { LeftArrow, RightArrow } from 'components/icons'

function SliderSection() {
  return (
    <section
      style={{
        background:
          'linear-gradient(180deg, rgba(12, 17, 44, 0) 0%, #0C112C 100%), linear-gradient(180deg, rgba(12, 17, 44, 0) 0%, #0C112C 100%), #2455EA',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <div className="mx-auto flex w-full flex-col items-center py-9 px-4 text-center sm:px-36 sm:pt-14">
        <h2 className="text-2xl font-bold leading-heading text-white xl:text-[28px] xxl:text-[42px]">
          Get your virtual ownership and earn profits
          <br />
          from Our RoboCo NFT Collection
        </h2>
        <img className="mt-20 w-[457px]" src={slider} />
        <div className="my-20 flex items-center gap-2 px-4 text-xs text-white xl:w-[450px] xl:text-xs xxl:text-base">
          <LeftArrow style={{ minWidth: 24 }} />
          <p>
            Early adopter via NFT ownership will be entitled to a base interest
            rate until the robotics solutions launch, a share of future revenue
            generated by the robots, and partner-exclusive service discounts
          </p>
          <RightArrow style={{ minWidth: 24 }} />
        </div>
      </div>
    </section>
  )
}

export default SliderSection
